FROM ubuntu:24.04

RUN apt update && \
    apt install -y git neovim python3

WORKDIR /workspace

RUN if [ -z "${GITHUB_TOKEN}" ]; then echo "GITHUB_TOKEN is not set"; exit 1; fi
RUN git clone https://${GITHUB_TOKEN}@github.com/avogatio/dotfiles.git
RUN git clone https://${GITHUB_TOKEN}@github.com/avogatio/bootkit.git
